font: &font Poppins Medium:pixelsize=18
awesome: &awesome Font Awesome 6 Free:style=solid:pixelsize=14
# catppuccin colors
fg: &fg cdd6f4ff
bg: &bg 181825ff
magenta: &magenta cba6f7ff
red: &red f38ba8ff
yellow: &yellow f9e2afff
green: &green a6e3a1ff
sky: &sky 89dcebff
sapphire: &sapphire 74c7ecff
blue: &blue 89b4faff
lavender: &lavender b4befeff
base: &base 1e1e2eff
crust: &crust 11111bff
bg_default: &bg_default { stack: [{ background: { color: *bg } }] }
bar:
  height: 34
  location: top
  font: *font
  spacing: 4
  margin: 2
  layer: bottom
  foreground: *fg
  background: *bg

  right:
    - cpu:
        poll-interval: 2500
        content:
          map:
            conditions:
              id < 0:
                - string: { text: " ", font: *font, foreground: *blue }
                - string: { text: "{cpu}%", foreground: *blue }
    - mem:
        poll-interval: 2500
        content:
          string: { text: " {used:mb} MB", font: *font, foreground: *red }
    - pipewire:
        anchors:
          volume: &volume
            conditions:
              muted: { string: { text: "󰝟 muted" } }
              ~muted:
                - ramp:
                    tag: cubic_volume
                    items:
                      - string: { text: " {cubic_volume}%", foreground: *sky }
                      - string: { text: " {cubic_volume}%", foreground: *sky }
                      - string: { text: " {cubic_volume}%", foreground: *sky }
        content:
          map:
            conditions:
              type == "sink":
                map:
                  <<: *volume
    - clock:
        content:
          - string: { text: " {date}", margin: 5, foreground: *magenta }
          - string: { text: "󰥔 {time}  ", foreground: *lavender }

  left:
    - river:
        anchors:
          - base: &river_base
              left-margin: 5
              right-margin: 5
              conditions:
                id == 1: { string: { text: 1, font: *font } }
                id == 2: { string: { text: 2, font: *font } }
                id == 3: { string: { text: 3, font: *font } }
                id == 4: { string: { text: 4, font: *font } }
                id == 5: { string: { text: 5, font: *font } }
                id == 6: { string: { text: 6, font: *font } }
                id == 7: { string: { text: 7, font: *font } }
                id == 8: { string: { text: 8, font: *font } }
                id == 9: { string: { text: 9, font: *font } }
                # id == 21: { string: { text: "scratchpad", font: *font } }
        content:
          map:
            on-click:
              left: sh -c "riverctl set-focused-tags $((1 << ({id} - 1)))"
              right: sh -c "riverctl toggle-focused-tags $((1 << ({id} -1)))"
              middle: sh -c "riverctl toggle-view-tags $((1 << ({id} -1)))"
            conditions:
              state == urgent:
                string:
                  foreground: *red
                  text: " {id}"
              state == focused:
                string:
                  foreground: *blue
                  text: " {id}"
              state == invisible && ~occupied: { empty: {} }
              state == invisible && occupied:
                string:
                  foreground: *fg
                  text: " {id}"
            <<: *river_base
    - foreign-toplevel:
        content:
          map:
            conditions:
              ~activated: { empty: {} }
              activated:
                - string: { text: "  {app-id}", foreground: *sapphire }
                - string: { text: ": {title}" }
  center:
    - mpd:
        host: /run/user/1000/mpd/socket
        content:
          map:
            conditions:
              state == playing:
                string: { text: "{artist} - {title}", foreground: *magenta }
