
[cursor]
thickness = 0.20

[window]
dimensions = { columns = 145, lines = 30 }
# blur = true
opacity = 1

[env]
TERM = "xterm-256color"

[font]
size = 14

[font.normal]
family = "Iosevka SS07"
style = "Medium"

[font.italic]
family = "Iosevka SS07"
style = "Italic"

[font.bold]
family = "Iosevka SS07"
style = "Bold"

[font.bold_italic]
family = "Iosevka SS07"
style = "Bold Italic"

[general]
import = ["~/.config/alacritty/catppuccin-mocha.toml"]
