local map = vim.api.nvim_set_keymap
local opts = { noremap = true, silent = true }

vim.g.mapleader = " "

-- custom mappings
map("n", "<leader>e", ":NvimTreeToggle<CR>", opts)
map("n", "<leader>h", ":set hlsearch!<CR>", opts)
map("n", "<leader>ps", ":PackerSync<CR>", opts)
map("n", "<leader>nt", ":tabnew<CR>", opts)
-- bufferline mappings
map("n", "<A-,>", ":BufferLineCyclePrev<CR>", opts)
map("n", "<A-.>", ":BufferLineCycleNext<CR>", opts)
map("n", "<A-<>", ":BufferLineMovePrev<CR>", opts)
map("n", "<A->>", ":BufferLineMoveNext<CR>", opts)
map("n", "<A-1>", ":BufferLineGoToBuffer 1<CR>", opts)
map("n", "<A-2>", ":BufferLineGoToBuffer 2<CR>", opts)
map("n", "<A-3>", ":BufferLineGoToBuffer 3<CR>", opts)
map("n", "<A-4>", ":BufferLineGoToBuffer 4<CR>", opts)
map("n", "<A-5>", ":BufferLineGoToBuffer 5<CR>", opts)
map("n", "<A-6>", ":BufferLineGoToBuffer 6<CR>", opts)
map("n", "<A-7>", ":BufferLineGoToBuffer 7<CR>", opts)
map("n", "<A-8>", ":BufferLineGoToBuffer 8<CR>", opts)
map("n", "<A-9>", ":BufferLineGoToBuffer 9<CR>", opts)
map("n", "<A-q>", ":BufferLineCloseLeft<CR>", opts)
map("n", "<A-e>", ":BufferLineCloseRight<CR>", opts)
map("n", "<A-c>", ":BufferLinePickClose<CR>", opts)
map("n", "<C-p>", ":BufferLinePick<CR>", opts)
map("n", "<leader>bd", ":BufferLineSortByDirectory<CR>", opts)
map("n", "<leader>be", ":BufferLineSortByExtension<CR>", opts)
-- telescope mappings
map("n", "<leader>ff", ":Telescope find_files<CR>", opts)
map("n", "<leader>fg", ":Telescope live_grep<CR>", opts)
map("n", "<leader>fp", ":Telescope project<CR>", opts)
map("n", "<leader>fb", ":Telescope file_browser<CR>", opts)
map("n", "<leader>fB", ":Telescope buffers<CR>", opts)
map("n", "<leader>fh", ":Telescope oldfiles<CR>", opts)
map("n", "<leader>fd", ":Telescope diagnostics<CR>", opts)
map("n", "<leader>fD", ":Telescope lsp_definitions<CR>", opts)
map("n", "<leader>fs", ":Telescope symbols<CR>", opts)
map("n", "<leader>fc", ":Telescope neoclip<CR>", opts)
map("n", "<leader>gf", ":Telescope git_files<CR>", opts)
map("n", "<leader>gc", ":Telescope git_commits<CR>", opts)
map("n", "<leader>gs", ":Telescope git_status<CR>", opts)
map("n", "<leader>gS", ":Telescope git_stash<CR>", opts)
map("n", "<leader>fH", ":Telescope command_history<CR>", opts)
map("n", "<leader>fM", ":Telescope media_files<CR>", opts)
map("n", "<leader>fm", ":Telescope marks<CR>", opts)
map("n", "<leader>cs", ":Telescope colorscheme<CR>", opts)
-- change splits
map("n", "<C-h>", "<C-w>h", opts)
map("n", "<C-j>", "<C-w>j", opts)
map("n", "<C-k>", "<C-w>k", opts)
map("n", "<C-l>", "<C-w>l", opts)
-- ToggleTerm
map("n", "<leader>tp", ":lua _PYTHON_TOGGLE()<CR>", opts)
map("n", "<leader>th", ":lua _HTOP_TOGGLE()<CR>", opts)
map("n", "<leader>tg", ":lua _LAZYGIT_TOGGLE()<CR>", opts)
map("n", "<leader>tn", ":lua _NODE_TOGGLE()<CR>", opts)
