# Configuration for Alacritty, the GPU enhanced terminal emulator.

window:
  # Window decorations
  decorations: none

  # Window title
  title: Alacritty

  # Allow terminal applications to change Alacritty's window title.
  dynamic_title: true

  # Window padding (changes require restart)
  padding:
    x: 5
    y: 5

  # Window class (Linux/BSD only):
  #class:
  # Application instance name
  #instance: Alacritty
  # General application class
  #general: Alacritty

  # GTK theme variant (Linux/BSD only)
  gtk_theme_variant: dark

  # Background opacity
  opacity: 1.0

  # Startup Mode (changes require restart)
  startup_mode: Maximized

scrolling:
  history: 10000
  multiplier: 3

# Font configuration
font:
  # Normal (roman) font face
  normal:
    family: Iosevka Mayukai Codepro
    style: Medium

  # Bold font face
  bold:
    family: Iosevka Mayukai Codepro
    style: Bold

  # Italic font face
  italic:
    family: Iosevka Mayukai Codepro
    style: Medium Italic

  # Bold italic font face
  bold_italic:
    family: Iosevka Mayukai Codepro
    style: Bold Italic

  # Point size
  size: 14.0

# If `true`, bold text is drawn using the bright color variants.
draw_bold_text_with_bright_colors: true

cursor:
  # Cursor style
  style:
    # Cursor shape
    shape: Block

    # Cursor blinking state
    blinking: Off

  # Vi mode cursor style
  vi_mode_style: None

  # Cursor blinking interval in milliseconds.
  blink_interval: 750

  # If this is `true`, the cursor will be rendered as a hollow box when the
  # window is not focused.
  unfocused_hollow: true

  # Thickness of the cursor relative to the cell width as floating point number
  thickness: 0.15

# Live config reload (changes require restart)
live_config_reload: true

# keybinds
key_bindings:
  - { key: Return, mods: Super, action: SpawnNewInstance }

# import colorschemes
import:
  - ~/.config/alacritty/colors.yml
