import = ["~/.config/alacritty/catppuccin-mocha.toml"]

[cursor]
thickness = 0.20

[window]
dimensions = { columns = 145, lines = 30 }
blur = true
opacity = 0.65

[env]
TERM = "xterm-256color"

[font]
size = 14

[font.bold]
family = "JetBrains Mono"
style = "Bold"

[font.bold_italic]
family = "JetBrains Mono"
style = "Bold Italic"

[font.italic]
family = "JetBrains Mono"
style = "Italic"

[font.normal]
family = "JetBrains Mono"
style = "Medium"
